kind = "web"
previewPath = "/"
title = "StayBnB"
version = "1.0.0"
id = "artifacts/staybnb"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19981

[services.development]
run = "pnpm --filter @workspace/staybnb run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/staybnb", "run", "build" ]
publicDir = "artifacts/staybnb/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19981"
BASE_PATH = "/"
